version: "3"
services:
  mssql:
    build: ./mssql
    init: true
    hostname:  mssql
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REGISTRY_GROUP}/contentstore:latest
    privileged: true
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    stop_grace_period: 120s
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SYSTEMX_CONTENTSTORE_PASSWORD}
      - MSSQL_PID=Express
    restart: always

    
  rs:
    build:
      context: ./rs
      args:
        SYSTEMX_INSTALLER_URL: ${SYSTEMX_INSTALLER_URL}
        SYSTEMX_INSTALLER_FILENAME: ${SYSTEMX_INSTALLER_FILENAME}
        SYSTEMX_REPORTINGSERVER_REPOSITORY_URL: ${SYSTEMX_REPORTINGSERVER_REPOSITORY_URL}
        SYSTEMX_REPORTINGSERVER_REPOSITORY: ${SYSTEMX_REPORTINGSERVER_REPOSITORY}
        #SYSTEMX_CONTENTSTORE_USERNAME: ${SYSTEMX_CONTENTSTORE_USERNAME}
        #SYSTEMX_CONTENTSTORE_PASSWORD: ${SYSTEMX_CONTENTSTORE_PASSWORD}
    hostname: rs
    depends_on:
      - mssql
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REGISTRY_GROUP}/reportingserver:11.2.4.1.1
    ports:
      - "5901:5901"
      - "6901:6901"
      - "9300:9300"
    volumes:
      - rs-configuration:/opt/hapec/SystemX/ReportingServer/configuration
      - rs-data:/opt/hapec/SystemX/ReportingServer/data
    stop_grace_period: 300s
    environment:
       #- SYSTEMX_RS_STARTUP=false
       - SYSTEMX_CONTENTSTORE_DATABASE=dbHAPECContentstore
       - SYSTEMX_CONTENTSTORE_USERNAME=${SYSTEMX_CONTENTSTORE_USERNAME}
       - SYSTEMX_CONTENTSTORE_PASSWORD=${SYSTEMX_CONTENTSTORE_PASSWORD}
    #   - SYSTEMX_INSTALLER_URL=${SYSTEMX_INSTALLER_URL}
    #   - SYSTEMX_INSTALLER_FILENAME=${SYSTEMX_INSTALLER_FILENAME}
    #   - SYSTEMX_REPORTINGSERVER_REPOSITORY_URL=${SYSTEMX_REPORTINGSERVER_REPOSITORY_URL}
    #   - SYSTEMX_REPORTINGSERVER_REPOSITORY=${SYSTEMX_REPORTINGSERVER_REPOSITORY}
#    volumes:
#      - shared:/shared      

volumes:
  mssql-data:
  rs-configuration:
  rs-data: