version: "3"
services:
  mssql:
    build: ./mssql
    init: true
    hostname:  mssql
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REGISTRY_GROUP}/contentstore:latest
    privileged: true
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    stop_grace_period: 120s
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SYSTEMX_CONTENTSTORE_PASSWORD}
      - MSSQL_PID=Express
    restart: always

    
  rs:
    build:
      context: ./rs
      args:
        SYSTEMX_INSTALLER_URL: ${SYSTEMX_INSTALLER_URL}
        SYSTEMX_INSTALLER_FILENAME: ${SYSTEMX_INSTALLER_FILENAME}
        SYSTEMX_REPORTINGSERVER_REPOSITORY_URL: ${SYSTEMX_REPORTINGSERVER_REPOSITORY_URL}
        SYSTEMX_REPORTINGSERVER_REPOSITORY: ${SYSTEMX_REPORTINGSERVER_REPOSITORY}
    hostname: rs
    depends_on:
      - mssql
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REGISTRY_GROUP}/reportingserver:11.2.4.1.1
    ports:
      - "5901:5901"
      - "6901:6901"
      - "9300:9300"
    volumes:
      - rs-configuration:/opt/hapec/SystemX/ReportingServer/configuration
      - rs-data:/opt/hapec/SystemX/ReportingServer/data
    stop_grace_period: 300s
    environment:
       - SYSTEMX_RS_STARTUP=false
       - SYSTEMX_RS_CONFIG_LOCK_REMOVAL=false
       - SYSTEMX_RS_ALLOW_ANONYMOUS_ACCESS=false
       - SYSTEMX_CONTENTSTORE_DATABASE=dbHAPECContentstore
       - SYSTEMX_CONTENTSTORE_USERNAME=${SYSTEMX_CONTENTSTORE_USERNAME}
       - SYSTEMX_CONTENTSTORE_PASSWORD=${SYSTEMX_CONTENTSTORE_PASSWORD}
       - SYSTEMX_KEYCLOAK_DISCOVERY_ENDPOINT=${SYSTEMX_KEYCLOAK_DISCOVERY_ENDPOINT}
       - SYSTEMX_KEYCLOAK_CLIENT_IDENTIFIER=${SYSTEMX_KEYCLOAK_CLIENT_IDENTIFIER}
       - SYSTEMX_KEYCLOAK_RETURN_URL=${SYSTEMX_KEYCLOAK_RETURN_URL}
       - SYSTEMX_KEYCLOAK_CLIENT_SECRET=${SYSTEMX_KEYCLOAK_CLIENT_SECRET}
       - SYSTEMX_KEYCLOAK_PRIVATE_KEY_PASSWORD=${SYSTEMX_KEYCLOAK_PRIVATE_KEY_PASSWORD}

  as:
    build:
      context: ./as
      args:
        SYSTEMX_JAVA_INSTALLER_URL: ${SYSTEMX_JAVA_INSTALLER_URL}
        SYSTEMX_JAVA_INSTALLER: ${SYSTEMX_JAVA_INSTALLER}
        SYSTEMX_ANALYTICSERVER_REPOSITORY_URL: ${SYSTEMX_ANALYTICSERVER_REPOSITORY_URL}
        SYSTEMX_ANALYTICSERVER_REPOSITORY: ${SYSTEMX_ANALYTICSERVER_REPOSITORY}
    hostname: as.cognos.local
    depends_on:
      - rs
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REGISTRY_GROUP}/analyticserver:2.0.9.16
    ports:
      - "5495:5495" # TM1 Admin Server plain
      - "5498:5498" # TM1 Admin Server ssl
      - "5500:5500" # TM1 Instance hapecAnalyticServer
      - "5901:5901" # VNC
      - "6901:6901" # noVNC
      - "9510:9510" # pmpsvc
    volumes:
      - as-configuration:/opt/hapec/SystemX/AnalyticServer/configuration
      - as-TM1Servers:/TM1Servers
    stop_grace_period: 300s
    environment:
       - SYSTEMX_AS_STARTUP=true
       - SYSTEMX_AS_IPV4_ADDRESS=${SYSTEMX_AS_IPV4_ADDRESS}
    networks: 
       macvlan:
         ipv4_address: ${SYSTEMX_AS_IPV4_ADDRESS}
    cap_add:
      - NET_ADMIN

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: "192.168.0.254"

volumes:
  mssql-data:
  rs-configuration:
  rs-data:
  as-configuration:
  as-TM1Servers: